######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

# Set XPS project settings var
variable xps_arch
variable xps_dev
variable xps_pkg
variable xps_spd

# Print mismatch data
proc _mismatch_ {} {
  variable xps_arch
  variable xps_dev
  variable xps_pkg
  variable xps_spd

  puts "Settings Mismatch:"
  puts "Current Project:"
  puts "   Family:  zynq"
  puts "   Device:  xc7z010"
  puts "   Package: clg400"
  puts "   Speed:   -1"
  puts "XPS Project: "
  puts "   Family:  $xps_arch"
  puts "   Device:  $xps_dev"
  puts "   Package: $xps_pkg"
  puts "   Speed:   $xps_spd"
}

# Load project
cd "/home/smahmood/Parallella-Projects/p7010hdmi/p7010hdmi.srcs/sources_1/system"
if { [xload xmp system.xmp] != 0 } {
  exit -1
}

# Current project settings
set pa_arch zynq
set pa_dev  xc7z010
set pa_pkg  clg400
set pa_spd  -1

# XMP project settings
set xps_arch [xget arch]
set xps_dev  [xget dev]
set xps_pkg  [xget package]
set xps_spd  [xget speedgrade]

# Perform settings check
if {[string equal -nocase $pa_arch $xps_arch] &&\
    [string equal -nocase $pa_dev  $xps_dev]  &&\
    [string equal -nocase $pa_pkg  $xps_pkg]  &&\
    [string equal -nocase $pa_spd  $xps_spd]} {
  exit 0
} else {
  _mismatch_
  exit -1
}

